### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method launchPdfActivity on channel com.pycampers.flutter_pdf_viewer)

### ISSUE THREAD

**Issue by zfha** [pycampers/flutter_pdf_viewer#29]
Dev enviroment run is ok?  but  `flutter build apk --release` then 
```
2019-07-09 10:07:10.738 4735-4897/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method launchPdfActivity on channel com.pycampers.flutter_pdf_viewer)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314)
    <asynchronous suspension>
    #1      PdfViewer._launchPdfActivity (package:flutter_pdf_viewer/flutter_pdf_viewer.dart:263)
    <asynchronous suspension>
    #2      PdfViewer.loadBytes (package:flutter_pdf_viewer/flutter_pdf_viewer.dart:301)
    <asynchronous suspension>
    #3      CRMPanState.onClickResource (package:youkeda_flutter/pages/crm_pan/index.dart:148)
    <asynchronous suspension>
    #4      PanPageWidgetState.build.<anonymous closure> (package:youkeda_flutter/pages/crm_pan/pan_page.dart:160)
    #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
    #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365)
    #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275)
    #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455)
    #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75)
    #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102)
    #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218)
    #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198)
    #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156)
    #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
    #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
```

**Comment by devxpy** [comment]
Looks like a dup of https://github.com/pycampers/flutter_pdf_viewer/issues/28. Let's track it over there.
